using System.Collections;
using System.Collections.Generic;
using UnityEngine.UI;
using UnityEngine;
using System;
using enumNameSpace;
using inputManager;

public class GameManager : MonoBehaviour
{
    //Interact modules Begins
    public Bed_1 bed_1_InteractionManager;
    public Coin coin_InteractionManager;
    //Interact modules End

    private Vector3 respawnPosition;
    public Vector3 RespawnPosition { set => respawnPosition = value; }

    public ImputManager imputManager;
    public Canvas g_canvas;
    public CameraManager CameraManager;

    public bool g_allowUI = true;
    public GameObject UIContainer;
    
    public Buttoner[] buttoners;
    public GameObject mainCharacter; 
    private Rigidbody2D mainCharacter_Rigidbody2D;
    public Collider2D nowGrounding;

    public float score = 0;
    public Text textline;

    public Collider2D nowInteracting;
    public bool isLaddering;
    private bool laddermode = false;
    public int g_jumpEnabledCount = 2;
    public int g_jumpEnabledLimit = 2;

    //public float g_touchGroundsjumpForce;
    //public float tGjF_init;

    public float g_accelerationX_origin = 1.5f;
    
    //private float tGjF_count; //TouchGroundLittleJump_Count
    
    public float g_VelocityJump = 8f;
    //private bool m_jumpBumper = true;

    public float g_restrictVelocityXAbs;
    public float g_restrictVelocityYAbs;

    public bool[] g_movementJurisdiction = new bool[4] { true, true, true, true};
    /*0=left , 1=right , 2=up , 3=down
     *true ==  
     */                                                                    
    public bool g_grounded = false;
    
    public float drag_set = 0.7f;
    private bool addDragflag = false;//false == addable ; true == added
    public float drag_decline_set = 1.6f; //second
    private  float drag_timeCounter = 0f;
    
    public float ladderSpeed = 3f;

    //lock == true ; unlock == false


    void Start()
    {
        coin_InteractionManager.gameObject.SetActive(true);
        mainCharacter_Rigidbody2D = mainCharacter.GetComponent<Rigidbody2D>();
        UIContainer.SetActive(g_allowUI);
    }

    public void GameOver()
    {
        print("gameOver \\(0ω0)/");
        CameraManager.locked = true;
        mainCharacter.SetActive(false);
        score = 0;
        coin_InteractionManager.Reset();
        bed_1_InteractionManager.Reset();
        mainCharacter_Rigidbody2D.velocity = new Vector2(0f, 0f);
        mainCharacter.transform.position = respawnPosition; // ???
        mainCharacter.SetActive(true);
        CameraManager.locked = false;
    }

    public void CharacterDie()
    {
        mainCharacter_Rigidbody2D.velocity = new Vector2(0f, 0f);
        mainCharacter.transform.position = respawnPosition;
    }

    public void GameStart()
    {
        print("gameStart _(:3 )∠_");
        CameraManager.locked = false;
        mainCharacter.gameObject.transform.position = new Vector2(0, 0);
        score = 0f;
        g_jumpEnabledCount = g_jumpEnabledLimit;
        mainCharacter.SetActive(true);
    }

    public bool AddJump()
    {
        if ( g_jumpEnabledCount < g_jumpEnabledLimit)
        {
            g_jumpEnabledCount++;
            return true;
        }
        return false;
    }

    public float AddScore(float n)
    {
        score += n;
        return score;
    }

    private void Print_Text(string tstr)
    {
        textline.text = tstr;
    }

    public void MainCharacterJump()
    {
        if (g_jumpEnabledCount > 0)
        {
            mainCharacter_Rigidbody2D.velocity = new Vector2(mainCharacter_Rigidbody2D.velocity.x, g_VelocityJump);
            g_jumpEnabledCount--;
        }
    }

    private void Update()
    {
        if(Input.GetKeyDown(KeyCode.Insert))
        {
            GameOver();
        }
        
        if (score>=8)
        {
            Print_Text("Score:" + (int)score + "You Win!!");
        }
        else
        {
            Print_Text("Score:" + (int)score);
        }
        
        //----movement----
        if (imputManager.status[(int)EnumStatus.Left] && (g_grounded || g_movementJurisdiction[0]) == true)
        {
            laddermode = false;
            addDragflag = false;
            if ((mainCharacter_Rigidbody2D.velocity + new Vector2(-g_accelerationX_origin, 0)).x <= -g_restrictVelocityXAbs)
                mainCharacter_Rigidbody2D.velocity += new Vector2(-g_restrictVelocityXAbs - mainCharacter_Rigidbody2D.velocity.x, 0);
            else
                mainCharacter_Rigidbody2D.velocity += new Vector2(-g_accelerationX_origin, 0);
        }
        else if(imputManager.status[(int)EnumStatus.Right] && (g_grounded || g_movementJurisdiction[1]) == true)
        {
            laddermode = false;
            addDragflag = false;
            if ((mainCharacter_Rigidbody2D.velocity + new Vector2(g_accelerationX_origin, 0)).x >= g_restrictVelocityXAbs)
                mainCharacter_Rigidbody2D.velocity += new Vector2(g_restrictVelocityXAbs - mainCharacter_Rigidbody2D.velocity.x, 0);
            else
                mainCharacter_Rigidbody2D.velocity += new Vector2(g_accelerationX_origin, 0);
        }
        else
        {
            addDragflag = true;
        }

        if (imputManager.status[(int)EnumStatus.Jump])
        {
            MainCharacterJump();
            imputManager.status[(int)EnumStatus.Jump] = false;
        }

        if (isLaddering == true) //Laddering_Collided
        {
            mainCharacter_Rigidbody2D.gravityScale = 0f;
            //[Tip][20210125]应接上动画切换...
            if (imputManager.status[(int)EnumStatus.Up])
            {
                laddermode = true;
                mainCharacter_Rigidbody2D.velocity = new Vector2(0f, +ladderSpeed);
            }
            else if (imputManager.status[(int)EnumStatus.Down])
            {
                laddermode = true;
                mainCharacter_Rigidbody2D.velocity = new Vector2(0f, -ladderSpeed);
            }

            else
            {
                if(laddermode)
                {
                    if (imputManager.status[(int)EnumStatus.Left])
                    {
                        laddermode = true;
                        mainCharacter_Rigidbody2D.velocity = new Vector2(-ladderSpeed, mainCharacter_Rigidbody2D.velocity.y);
                    }
                    else if (imputManager.status[(int)EnumStatus.Right])
                    {
                        laddermode = true;
                        mainCharacter_Rigidbody2D.velocity = new Vector2(ladderSpeed, mainCharacter_Rigidbody2D.velocity.y);
                    }

                    mainCharacter_Rigidbody2D.velocity = new Vector2(0f, 0f);
                }
                else
                {
                    mainCharacter_Rigidbody2D.gravityScale = 1f;
                }
            }
        }
        else
        {
            mainCharacter_Rigidbody2D.gravityScale = 1f;
        }
        //----endof movement----

        //----movement----
        if ( imputManager.status[(int)EnumStatus.Interact] && nowInteracting == true)
        {
            //interact
            nowInteracting.transform.parent.gameObject.GetComponent<Bed_1>().Interact(int.Parse(nowInteracting.gameObject.name));
        }
        
        drag_timeCounter = (addDragflag) ?  (drag_timeCounter + Time.deltaTime): 0f ;
        mainCharacter_Rigidbody2D.drag = (drag_set * (1f-(drag_timeCounter / drag_decline_set))<=0f) ? 0f : drag_set * (1f - (drag_timeCounter / drag_decline_set));

        buttoners[(int)EnumStatus.Interact].gameObject.GetComponent<Button>().interactable = nowInteracting ? true : false;
        buttoners[(int)EnumStatus.Up].gameObject.GetComponent<Button>().interactable =buttoners[(int)EnumStatus.Up].gameObject.GetComponent<Button>().interactable = isLaddering ? true : false;

    }

}
